name: 🚀 Enhancement
description: Suggest an enhancement to an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement!

  - type: textarea
    id: current-feature
    attributes:
      label: Current feature
      description: Which existing feature would you like to enhance?
      placeholder: |
        The current feature works like...
    validations:
      required: true

  - type: textarea
    id: enhancement-description
    attributes:
      label: Enhancement description
      description: Describe the enhancement you're suggesting
      placeholder: |
        I would like this feature to...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this enhancement improve the project?
      placeholder: |
        This enhancement would make it easier to...
    validations:
      required: true

  - type: textarea
    id: debug-info
    attributes:
      label: Platform info
      description: Run `poof debug` and paste the output here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any other information that might be helpful
      placeholder: |
        Screenshots, mockups, or additional context...
    validations:
      required: false

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is this issue already reported?
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched the existing issues and this has not been reported yet
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT_URL)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
